CREATE DATABASE tarea3;
USE tarea3;
CREATE TABLE CIType (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CI (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    SerialNumber NVARCHAR(100),
    Version NVARCHAR(50),
    AcquisitionDate DATE,
    CurrentStatus NVARCHAR(50),
    PhysicalLocation NVARCHAR(255),
    Owner NVARCHAR(100),
    SecurityLevel NVARCHAR(50),
    Compliance NVARCHAR(50),
    ConfigStatus NVARCHAR(50),
    LicenseNumber NVARCHAR(100),
    ExpirationDate DATE,
    TypeId INT NOT NULL FOREIGN KEY REFERENCES CIType(Id),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE CIRelationship (
    Id INT IDENTITY PRIMARY KEY,
    FromCIId INT NOT NULL FOREIGN KEY REFERENCES CI(Id),
    ToCIId INT NOT NULL FOREIGN KEY REFERENCES CI(Id),
    RelationshipType NVARCHAR(100)
);

CREATE TABLE CIDocumentation (
    Id INT IDENTITY PRIMARY KEY,
    CIId INT NOT NULL FOREIGN KEY REFERENCES CI(Id),
    DocURL NVARCHAR(500),
    IncidentURL NVARCHAR(500)
);

CREATE TABLE CIChangeLog (
    Id INT IDENTITY PRIMARY KEY,
    CIId INT NOT NULL FOREIGN KEY REFERENCES CI(Id),
    ChangeDate DATETIME NOT NULL DEFAULT GETDATE(),
    ChangeDescription NVARCHAR(MAX),
    ChangedBy NVARCHAR(100)
);

ALTER TABLE CI
ADD Environment NVARCHAR(20) CHECK (Environment IN ('DEV', 'QA', 'PROD'));